backend:
  name: github
  repo: RealtyOffer/realty-offer-frontend
  api_root: https://api.github.com
  branch: develop
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    editor:
      preview: false
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: "Meta Title", name: metaTitle, widget: string }
      - { label: "Meta Description", name: metaDescription, widget: string }
      - { label: "Meta Keywords", name: metaKeywords, widget: string }
      - { label: "Category", name: "category", widget: "select", options: [
          { label: "Consumer News", value: "consumer" },
          { label: "Agent News", value: "agent" }
        ] }
      - { label: Title, name: title, widget: string }
      - { label: 'Publish Date', name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: 'Featured Post', name: featuredpost, widget: boolean, required: false }
      - { label: 'Featured Image', name: featuredimage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: select, multiple: true, min: 1, options:
          [
          "Real Estate Agents",
          "Home Buying",
          "Home Selling",
          "Foreclosure",
          "Real Estate Market Trends",
          "Real Estate Tips",
          "Residential",
          "Commercial",
          "Mortgage",
          ]
        }
      - { label: 'Lead Form Title', name: leadFormTitle, widget: string }
      - { label: 'Lead Form Body', name: leadFormBody, widget: text }
      - { label: 'Lead Form CTA Text', name: leadFormCTAText, widget: string }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Sub Heading", name: heroSubheading, widget: string }
          - { label: "Hero CTA", name: heroCTA, widget: string }
          - {
            label: "Hero Nav",
            name: heroNav,
            widget: list,
            fields:
              [
                { label: "Hero CTA Link", name: heroLink, widget: string },
                { label: "Hero Carousel Nav Text", name: heroNavText, widget: string },
                { label: "Hero Carousel Nav Icon", name: heroNavIcon, widget: string, hint: 'Copy an icon name from https://react-icons.github.io/react-icons/icons?name=fa' },
              ],
          }
          - { label: "Section 1 Heading", name: sectionOneHeading, widget: string }
          - {
            label: "Section 1",
            name: sectionOne,
            widget: list,
            fields:
              [
                { label: "Main Image", name: mainImage, widget: image },
                { label: "Secondary Image", name: secondaryImage, widget: image },
                { label: "Heading", name: heading, widget: string },
                { label: "Content", name: content, widget: string },
                { label: "CTA Text", name: callToActionText, widget: string },
                { label: "CTA Link", name: callToActionLink, widget: string },
                
              ],
          }
          - { label: "Section 2 Heading", name: sectionTwoHeading, widget: string }
          - { label: "Section 2 Content", name: sectionTwoContent, widget: string }
          - { label: "Section 2 List Heading", name: sectionTwoListHeading, widget: string }
          - {
            label: "Section 2 List Items",
            name: sectionTwoListItems,
            widget: list,
            fields: [{ label: "Item", name: item, widget: string }],
          }
          - { label: "Section 3 Heading", name: sectionThreeHeading, widget: string }
          - { label: "Section 3 Content", name: sectionThreeContent, widget: string }
          - { label: "Section 4 Heading", name: sectionFourHeading, widget: string }
          - { label: "Section 4 Content", name: sectionFourContent, widget: string }
          - { label: "Section 4 Logos Heading", name: sectionFourLogosHeading, widget: string }
          - {
            label: "Section 4 Logos",
            name: sectionFourLogos,
            widget: list,
            fields: [{ label: "Logo", name: logo, widget: image }],
          }
          - { label: "Section 5 Heading", name: sectionFiveHeading, widget: string }
          - { label: "Section 5 Content", name: sectionFiveContent, widget: string }
          - {
            label: "Section 5 Cards",
            name: sectionFiveCards,
            widget: list,
            fields: [
              { label: "Image", name: image, widget: image },
              { label: "Heading", name: heading, widget: string },
              { label: "Content", name: content, widget: string },
              { label: "CTA Text", name: callToActionText, widget: string },
              { label: "CTA Link", name: callToActionLink, widget: string },
            ],
          }
          - {
            label: "Testimonial",
            name: testimonials,
            widget: list,
            fields:
              [
                { label: Quote, name: quote, widget: string },
                { label: Author, name: author, widget: string },
                { label: Avatar, name: avatar, widget: image },
              ],
          }
      - file: "src/pages/buy.md"
        label: "Buy Page"
        name: "buy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "buy",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Sub Heading", name: heroSubheading, widget: string }
          - { label: "Section 1 Heading", name: sectionOneHeading, widget: string }
          - { label: "Section 1 Sub Heading", name: sectionOneSubheading, widget: string }
          - { label: "Section 1 Image", name: sectionOneImage, widget: image }
          - { label: "Section 1 Content", name: sectionOneContent, widget: string }
          - { label: "Section 2 Heading", name: sectionTwoHeading, widget: string }
          - { label: "Section 2 Sub Heading", name: sectionTwoSubheading, widget: string }
          - { label: "Section 2 Image", name: sectionTwoimage, widget: image }
          - { label: "Section 2 Content", name: sectionTwoContent, widget: string }
          - { label: "Section 3 Heading", name: sectionThreeHeading, widget: string }
          - {
            label: "Section 3 List Items",
            name: sectionThreeList,
            widget: list,
            fields: [
              { label: "Text", name: text, widget: string },
              { label: 'Icon', name: icon, widget: string, hint: 'Copy an icon name from https://react-icons.github.io/react-icons/icons?name=fa'},
            ],
          }
          - { label: "Section 4 Heading", name: sectionFourHeading, widget: string }
          - { label: "Section 4 Subheading", name: sectionFourSubheading, widget: string }
          - {
            label: "Testimonial",
            name: testimonials,
            widget: list,
            fields:
              [
                { label: Quote, name: quote, widget: string },
                { label: Author, name: author, widget: string },
                { label: From, name: from, widget: string },
                { label: Avatar, name: avatar, widget: image },
                { label: Saved, name: saved, widget: string },
              ],
          }
      - file: "src/pages/frequently-asked-questions.md"
        label: "FAQ Page"
        name: "frequently-asked-questions"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "frequently-asked-questions",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Subheading", name: heroSubheading, widget: string }
          - {
              label: "Consumer FAQ",
              name: consumerFaq,
              widget: object,
              fields:
                [
                  {
                    label: "FAQ Item",
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answer, name: answer, widget: markdown },
                      ],
                  },
                ],
            }
          - {
              label: "Agent FAQ",
              name: agentFaq,
              widget: object,
              fields:
                [
                  {
                    label: "FAQ Item",
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answer, name: answer, widget: markdown },
                      ],
                  },
                ],
            }
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: Mission, name: mission, widget: markdown }
          - { label: Content, name: content, widget: markdown }
          - {
              label: "Team Members",
              name: teamMembers,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Bio, name: bio, widget: markdown },
                  { label: Avatar, name: avatar, widget: image },
                ],
            }
      - file: "src/pages/press.md"
        label: "Press"
        name: "press"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "press-page",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - {
            label: "Press Item",
            name: pressItems,
            widget: list,
            fields:
              [
                { label: Date, name: date, widget: date, format: 'MMM Do YY' },
                { label: Title, name: title, widget: string },
                { label: Excerpt, name: excerpt, widget: text },
                { label: Link, name: link, widget: string },
              ],
          }
      - file: "src/pages/partners.md"
        label: "Partners"
        name: "partners"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "partners-page",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: HeroHeading, name: heroHeading, widget: string }
          - { label: HeroSubheading, name: heroSubheading, widget: string }
          - { label: "Section One Heading", name: sectionOneHeading, widget: string }
          - { label: "Section One Content", name: sectionOneContent, widget: markdown }
          - { label: "Youtube Video ID", name: youtubeVideoId, widget: string }
          - { label: "Section Two Heading", name: sectionTwoHeading, widget: string }
          - { label: "Section Two Content", name: sectionTwoContent, widget: markdown }
          - { label: "Section Three Heading", name: sectionThreeHeading, widget: string }
          - { label: "Section Three Content", name: sectionThreeContent, widget: markdown }
          - { label: "Lead Form Title", name: leadFormTitle, widget: string }
          - { label: "Lead Form Body", name: leadFormBody, widget: string }
      - file: "src/pages/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "terms",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/pilot-terms.md"
        label: "Pilot Terms"
        name: "pilot-terms"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "pilot-terms",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/agents.md"
        label: "Agents Page"
        name: "agents"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "agents",
            }
          - { label: "Meta Title", name: metaTitle, widget: string }
          - { label: "Meta Description", name: metaDescription, widget: string }
          - { label: "Meta Keywords", name: metaKeywords, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: HeroMobileImage, name: mobileHeroImage, widget: image }
          - { label: "Hero Heading", name: heroHeading, widget: string }
          - { label: "Hero Subheading", name: heroSubheading, widget: markdown }
          - { label: "Section 1 Heading", name: sectionOneHeading, widget: string }
          - { label: "Section 1 SubHeading", name: sectionOneSubheading, widget: string }
          - { label: "Section 1 Image", name: sectionOneImage, widget: image }
          - { label: "Section 1 Content", name: sectionOneContent, widget: string }
          - { label: "Section 2 Heading", name: sectionTwoHeading, widget: string }
          - {
              label: "Section 2 Steps",
              name: sectionTwoSteps,
              widget: list,
              fields:
                [
                  { label: heading, name: heading, widget: string },
                  { label: content, name: content, widget: string },
                  { label: Image, name: image, widget: image},
                ],
            }
          - { label: "Section 3 Heading", name: sectionThreeHeading, widget: string }
          - { label: "Section 3 Content", name: sectionThreeContent, widget: markdown }
          - { label: "Section 3 Row One", name: sectionThreeRowOne, widget: string }
          - { label: "Section 3 Row Two", name: sectionThreeRowTwo, widget: string }
          - { label: "Section 4 Heading", name: sectionFourHeading, widget: string }
          - { label: "Section 4 Content", name: sectionFourContent, widget: markdown }
          - { label: "Section 4 Image", name: sectionFourImage, widget: image }
          - { label: "Section 5 Heading", name: sectionFiveHeading, widget: string }
          - { label: "Section 5 Content", name: sectionFiveContent, widget: markdown }
          - { label: "Section 5 Background Image", name: sectionFiveBackgroundImage, widget: image }
          - { label: "Section 6 Heading", name: sectionSixHeading, widget: string }
          - { label: "Section 6 Subheading", name: sectionSixSubheading, widget: string }
          - {
            label: "Testimonial",
            name: testimonials,
            widget: list,
            fields:
              [
                { label: Quote, name: quote, widget: string },
                { label: Author, name: author, widget: string },
                { label: From, name: from, widget: string },
                { label: Avatar, name: avatar, widget: image },
                { label: Saved, name: saved, widget: string },
              ],
          }
      - file: "src/pages/blog/index.md"
        label: "Blog Index Page"
        name: "blog-index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "blog-index-page",
            }
          - { label: Alert, name: alert, widget: string }
          - { label: Title, name: title, widget: hidden }
          - { label: Body, name: body, widget: hidden }
          - { label: HeroImage, name: heroImage, widget: hidden }
