# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings. We use 'master' branch for this project
[context.production.environment]
  ENVIRONMENT = "PRODUCTION"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.develop.environment] # 'develop' is a branch name
  ENVIRONMENT = "DEVELOP"

[[redirects]]
  from = '/consumer/*'
  to = '/consumer//index.html'
  status = 200

[[redirects]]
  from = '/agent/*'
  to = '/agent/index.html'
  status = 200

[[redirects]]
  from = '/admin/*'
  to = '/admin/index.html'
  status = 200